[project]
name = 'Urban-Planning-and-Development-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.community-improvement-fund]
path = 'contracts/community-improvement-fund.clar'
clarity_version = 2
epoch = 2.5

[contracts.construction-project-management]
path = 'contracts/construction-project-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.debris-tracker]
path = 'contracts/debris-tracker.clar'
clarity_version = 2
epoch = 2.5

[contracts.funding-pool_]
path = 'contracts/funding-pool_.clar'
clarity_version = 2
epoch = 2.5

[contracts.space-debris-token]
path = 'contracts/space-debris-token.clar'
clarity_version = 2
epoch = 2.5

[contracts.urban-development-proposal]
path = 'contracts/urban-development-proposal.clar'
clarity_version = 2
epoch = 2.5

[contracts.verification-system]
path = 'contracts/verification-system.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
